# input file
knowledge_graph: 'datasets/primekg/kg.csv'

# Subset file
subset_file: 'datasets/primekg/subset_kg.csv'

# GNN parameters
epochs: 2
learning_rate: 0.0001

# output directory
output_dir: 'output/'